import type { Metadata } from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Nav from "@/src/components/Nav";
import Form from "@/src/components/Form";
import Footer from "@/src/components/Footer";

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Unidotaciones del Caribe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={inter.className}
      >
        <Nav/>
        {children}
        <Form/>
        <Footer/>
      </body>
    </html>
  );
}
