import type { Metadata } from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Nav from "@/src/components/Nav";
import Footer from "@/src/components/Footer";

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Unidotaciones del Caribe",
  description: "Generated by create next app",
  openGraph: {
    title: "Uni Dotaciones del Caribe",
    description: "Uni Dotaciones del Caribe",
    type: "website",
    images: {
      url: "https://firebasestorage.googleapis.com/v0/b/fb-picporter.appspot.com/o/HADA%2FPreviewUnidotaciones.png?alt=media&token=a9f9b4ef-e675-4e4a-bee2-ab24cdd9c106",
      width: "1200",
      height: "630",
      alt: "Imagen descriptinva de la web",
    },
    siteName: "Uni Dotaciones del Caribe",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`bg-[#F8F8F8] ${inter.className}`}
      >
        <Nav/>
        {children}
        {/* <Form/> */}
        <Footer/>
      </body>
    </html>
  );
}
